# takes the point file and the weight file that are generated by simpoint
# generates a file that has weights and starting points together

import sys
array = []
ptsfile=sys.argv[1]
wfile=sys.argv[2]
outfile=sys.argv[3]
with open(ptsfile, "r") as pts, open(wfile,"r") as weights:
    for line, line2 in zip(pts, weights):
        array.append((line.split()[0], line2.split()[0]))
    print array
with open(outfile, 'w') as f:
    for i in array:
        f.write("\t".join(i))
        f.write("\n")
print (ptsfile,wfile,outfile)
